# Generated by Django 3.1.4 on 2020-12-04 14:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('creation_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('thanks', models.IntegerField(default=0)),
                ('reports', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('creation_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('hugs', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommentAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('creation_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('reports', models.IntegerField(default=0)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secret.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='secret_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secret.secret'),
        ),
    ]
